language: node_js
node_js:
    - "0.12"

script:
- npm run test:cov

branches:
    only:
        - master
        - dev

install:
    - npm install

cache:
    directories:
        - node_modules

addons:
  code_climate:
    repo_token: 124ff5d713849631cd9745eda71833a3029f5e9436a066fcc47bdbd88c1dfb9b

before_script:
    - export DISPLAY=:99.0
    - sh -e /etc/init.d/xvfb start

script:
    - npm test